# Generated by Django 4.1.6 on 2024-03-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SchoolProject.schoolclass'),
            preserve_default=False,
        ),
    ]
