# Generated by Django 4.1.6 on 2024-03-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolProject', '0003_remove_question_answer_answer_is_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='answer',
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolProject.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolProject.test')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ManyToManyField(related_name='questions', through='SchoolProject.TestQuestion', to='SchoolProject.test'),
        ),
    ]
